package com.hashedin.hu.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Movie")
public class Movie {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @JsonIgnore
    @DynamoDBAttribute
    private String imdbId;
    @DynamoDBAttribute
    private String title;

    @JsonIgnore
    @DynamoDBAttribute
    private String dateOfPublish;
    @DynamoDBAttribute
    private String year;
    @DynamoDBAttribute
    private String genre;
    @DynamoDBAttribute
    private String duration;
    @DynamoDBAttribute
    private String country;
    @JsonIgnore
    @DynamoDBAttribute
    private String language;

    @JsonIgnore
    @DynamoDBAttribute
    private String director;

    @JsonIgnore
    @DynamoDBAttribute
    private String writer;

    @JsonIgnore
    @DynamoDBAttribute
    private String productionCompany;

    @JsonIgnore
    @DynamoDBAttribute
    private String actors;

    @JsonIgnore
    @DynamoDBAttribute
    private String description;

    @JsonIgnore
    @DynamoDBAttribute
    private String avgVote;

    @JsonIgnore
    @DynamoDBAttribute
    private String vote;

    @DynamoDBAttribute
    private String budget;

    @JsonIgnore
    @DynamoDBAttribute
    private String usaGrossIncome;

    @JsonIgnore
    @DynamoDBAttribute
    private String worldwideGrossIncome;

    @JsonIgnore
    @DynamoDBAttribute
    private String metaScore;

    @DynamoDBAttribute
    private String userReview;

    @JsonIgnore
    @DynamoDBAttribute
    private String criticsReview;

    public Movie(String title, String year, String genre, String duration, String country, String language) {
        this.title = title;
        this.year = year;
        this.genre = genre;
        this.duration = duration;
        this.country = country;
        this.language = language;
    }

    public Movie(String imdbId, String title, String dateOfPublish, String year, String genre, String duration,
                 String country, String language, String director, String writer, String productionCompany,
                 String actors, String description, String avgVote, String vote, String budget, String usaGrossIncome,
                 String worldwideGrossIncome, String metaScore, String userReview, String criticsReview) {
        this.imdbId = imdbId;
        this.title = title;
        this.dateOfPublish = dateOfPublish;
        this.year = year;
        this.genre = genre;
        this.duration = duration;
        this.country = country;
        this.language = language;
        this.director = director;
        this.writer = writer;
        this.productionCompany = productionCompany;
        this.actors = actors;
        this.description = description;
        this.avgVote = avgVote;
        this.vote = vote;
        this.budget = budget;
        this.usaGrossIncome = usaGrossIncome;
        this.worldwideGrossIncome = worldwideGrossIncome;
        this.metaScore = metaScore;
        this.userReview = userReview;
        this.criticsReview = criticsReview;
    }
}